name: Build Web
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dot Net restore
        run: dotnet restore dot-net-core.csproj 
      - name: Run a one-line script
        run: dotnet build dot-net-core.csproj --configuration Release --no-restore
      - run: dotnet publish -c Release -o ./publish --no-build
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: web
          path: publish
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name : Get artifacts
        uses: actions/download-artifact@v7
        with:
          name: web
      - name: output content
        run: ls
