name: Build Web
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dot Net restore
        run: dotnet restore dot-net-core.csproj 
      - name: Run a one-line script
        run: dotnet build dot-net-core.csproj --configuration Release --no-restore
